### ISSUE TITLE
ZIM backend : infinite loop when trying to display some articles

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-html5#106]
I did not manage to open any of wikipedia_fr_all_09_2012.zim
In wikipedia_fr_solanaceae_08_2012.zim , I can open Acnistus, but not Accueil or Agouman
In wikipedia_en_all_simple_nopic_2015-02.zim, I can open most of the articles, but not "1 Maccabees" and a few others

**Comment by peter-x** [comment]
These might be redirects, redirects are not implemented yet.

**Comment by kelson42** [comment]
Yes, they are (redirects).

**Comment by mossroy** [comment]
Things have really improved with the handling of redirects in #118 
But there are still some articles that do not display (for example the first "America The Beautiful" in the Ray Charles archive) : it's probably another cause

**Comment by mossroy** [comment]
The remaining issues are probably related to redirects too. So I guess there are still bugs in the implementation of redirects.
Symptom : the article does not display, and the browser eats 100% of one CPU (infinite loop, I suppose)
Examples in the Ray Charles ZIM file : 
- "America The Beautiful", "America the beautiful" and "America, the Beautiful" do not work, but "America the Beautiful" works
- "Bein Green" and "Being Green" do not work, but "Bein' Green" works

**Comment by mossroy** [comment]
For both examples, it's an infinite loop in redirections.
For "America The Beautiful", it reads in the backend that it's at offset 6206, which is a redirect with redirectTarget 11.
It leads to "America the beautiful" at offset 6332, which is also a redirect, with redirectTarget 11 too.
And then it loops on this same entry forever.

Is it a bug in the ZIM file or in the app?

**Comment by mossroy** [comment]
It's not a bug in the ZIM file, as it works correctly with kiwix desktop application.
It's more probably a bug in the backend

**Comment by mossroy** [comment]
I added a unit test on this issue in branch unit-tests-on-redirection-issues

**Comment by kelson42** [comment]
@mossroy 
in wikipedia_en_ray_charles_2015-06.zim, "America The Beautiful" is indeed a redirect (it points ot index 11 like you have mentioned. That said, at index 11, this is "America the Beautiful" (and not "America the beautiful") and "America the Beautiful" is not a redirect. It's the article which needs to be displayed. "America the beautiful" is at index 11... so maybe this is simply and counting issue in the openByIndex() kind of function?

Here an extract of zimdump -l -i wikipedia_en_ray_charles_2015-06.zim

url: America,_the_Beautiful.html
        title:           America, the Beautiful
        idx:             9
        namespace:       A
        type:            redirect
        redirect index:  11
url: America_The_Beautiful.html
        title:           America The Beautiful
        idx:             10
        namespace:       A
        type:            redirect
        redirect index:  11
url: America_the_Beautiful.html
        title:           America the Beautiful
        idx:             11
        namespace:       A
        type:            article
        mime-type:       text/html
        article size:    32761
url: America_the_beautiful.html
        title:           America the beautiful
        idx:             12
        namespace:       A
        type:            redirect
        redirect index:  11
