### ISSUE TITLE
ZIM backend : handle splitted ZIM files, so that to be able to use big archives on FAT32 filesystems

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-html5#113]
*.zimaa, *.zimab

**Comment by mossroy** [comment]
If it's too complicated to handle, we might see if Firefox OS supports exFAT?

**Comment by mossroy** [comment]
Firefox OS does not currently support ExFAT. See https://bugzilla.mozilla.org/show_bug.cgi?id=1180334
gerard-majax (a Mozilla developer) thinks it should not be very complicated to implement. But it does not seem to be on any roadmap for now.

Handling spliited ZIM files is a workaround only for some archives : the complete English wikipedia content already does not fit in 32GB. See http://download.kiwix.org/zim/wikipedia/?C=S;O=D
If I understood correctly, you need a SDXC card to fit in. And the recommended filesystem for SDXC cards is exFAT

**Comment by kelson42** [comment]
Any SD card can work with splited ZIM files. It's important to handle splitted ZIM files, this should be easy.

**Comment by mossroy** [comment]
I also tried an ext4-formatted SD-card, and its content was not recognized by Firefox OS either
