### ISSUE TITLE
Load ZIM welcome page per default

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-html5#126]
At the time of the ZIM file loading, the ZIM file welcome page should be loaded per default. This is better than having a blank page.

**Comment by mossroy** [comment]
Good idea. It would also be a way to easily identify which archive is in use.
I did not know there was a welcome page in ZIM files.
How do I find it? Does it always have the same name in every ZIM file?

**Comment by kelson42** [comment]
The information is in the header of the ZIM file:
http://www.openzim.org/wiki/ZIM_file_format

jszim should provide a method to get the URL.

**Comment by kelson42** [comment]
This feature request is important, user might be not smart enough to start to type in the search box.
