### ISSUE TITLE
Unit tests do not all work on Chromium/Chrome

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-html5#131]
It's probably because there is a race condition somewhere, and we're lucky on Firefox and not on Chromium.
There's probably a place where I should wait for something to be completed before starting another one (with a callback or a Promise)

**Comment by sharun-s** [comment]
Main issue lies in sort order of split zims. There are other unrelated small changes listed below to get tests to run. Runs on Chrome/Firefox/Edge by just clicking on the html file (no localserver reqd).
 
1. use --allow-file-access-from-files when starting Chrome 
	chrome does not support xhr for "file://"" protocol unless the flag is set
2. remove xhr.status==200 check in makeblobrequest. 
	It fails in chrome even though the blobs are read but xhr.status is set to 0. Probably related to above policy.
3. fileArray.sort() in zimFile.js fromFileArray(fileArray) needs to be passed a comparison function to sort by blob "name"
	fileArray.sort() on Chrome was sorting blob objects differently than Firefox and Edge. 
	Reading the first 80 bytes of the fileArray[0] to retrieve zim header details then fails causing tests to fail.
	NOTE: If array size is 10 or less the blob sort order is the same across all 3 browsers. So best to test with larger than 10.
4. For Edge, changed toSource() to toString() in the load Image 'm/RayCharles_AManAndHisSoul.jpg' test	
5. [Optional] update qunit to 2.3.1 as QUnit.asyncTest is deprecated.

**Comment by mossroy** [comment]
Woha, that's a precise and complete analysis : thanks a lot for this valuable comment!
I suppose you modified the code to come to these conclusions : maybe you could share your modifications through some pull requests?

**Comment by sharun-s** [comment]
Will try. I haven't used Git much and never really used GitHub. How long do you think it will take? If it's not too complicated, could you please outline the basic steps. Thanks.

**Comment by mossroy** [comment]
Here are the basic steps to do that : 
- fork the git repository in Github : https://help.github.com/articles/fork-a-repo/
- make a local copy of your forked repo on your computer, with `git clone`
- modify the source code locally, and test it
- commit your modifications locally (`git add`, then `git commit`) with a meaningful commit message
- push your modifications to Github (`git push`)
- in the Github interface, go to the code tab of your forked repo, which should provide a button to create a pull request from your modified code

If you plan to make several pull requests, it would be better to create branches before modifying the code, but one step at a time...
