### ISSUE TITLE
In some cases, clicking on an article after a search does not display the right one

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-html5#133]
It does not seem to happen on the first search : only after having displayed a few articles, and returning to the search again.

I have to find a reproducible use-case, and check if it's related to the service-worker or not.
Workaround : close the browser tab or restart the browser (reload the page does not seems to be enough, at least in some cases)

**Comment by mossroy** [comment]
Here is a test-case in the Ray Charles ZIM file : open the article "Raelettes".
On Kiwix desktop, it redirects to "The Raelettes".
On this app, it leads to "Ray Charles".

It happens both in jQuery or Service Worker modes.
It might be the same bug in the backend as in #106

**Comment by mossroy** [comment]
It's probably a bug in the redirections code of the ZIM backend.
I added a unit test on this in branch unit-tests-on-redirection-issues

**Comment by kelson42** [comment]
I would try to fix #106 first... maybe this one will be fixed at the same time... We can be optimistic...
