### ISSUE TITLE
On some ZIM files, the images and some articles read in the backend have a 0 octet size

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-html5#156]
For example I/m/Ciudad.svg.png or A/Région_française.html or A/Langues_nilo-sahariennes.html on wikipedia_fr_all_2015-11
In kiwix desktop, this image and articles display fine.

The CSS are working fine on this ZIM file (at least most of them).

**Comment by mossroy** [comment]
This seems to happen only on big ZIM files, for example :
wikipedia_fr_all_09_2012.zim (15 GB)
wikipedia_fr_all_2015-11.zim (18 GB)
It does not seem to happen on smaller ones, for example : 
wikinews_fr_all_2015-11.zim (173 MB)
wikiquote_fr_all_2015-11.zim (28 MB)
wikinews_sq_all_2015-09.zim (5 MB)
wikiquote_nl_all_2015-11.zim (7 MB)

It might be the same cause as #133, I don't know.

**Comment by chriseth** [comment]
*sigh* this could be a javascript integer precision restriction...

**Comment by mossroy** [comment]
Based on the notes at the end of https://developer.mozilla.org/en-US/docs/Web/API/Blob/slice , it should work with unsigned 64-bit integers, which should be more than enough?

**Comment by peter-x** [comment]
No, that is not enough, Javascript's numbers usually have only 32 bits
of precision.

**Comment by mossroy** [comment]
If it's a file size limit, it seems to be around 2GB.
For example : wikibooks_en_all_2015-11.zim works (1.4 GB), but oer4schools_en_all_2015-11.zim does not (2.6GB)

**Comment by peter-x** [comment]
Exactly, 2 GB is the limit for signed 32 bit numbers. This mean we have to encode offsets as pairs of numbers and implement our own addition...

**Comment by mossroy** [comment]
If I understood correctly https://stackoverflow.com/questions/307179/what-is-javascripts-highest-integer-value-that-a-number-can-go-to-without-losin : 
- The Integer type in ECMAScript has a maximum value of 2^53-1 on recent implementations (which is more than enough) : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER
- But the bitwise operations only handle 32-bit precision : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators
(I might be wrong : it's what I read, I did not test)

So maybe a solution would be to replace the bitwise operations by something else?

A completely different approach of the problem would be to implement splitted ZIM files (#113 : I suppose the 2.1GB size of the splitted files correspond to the 32-bit precision), and support only them in the short term.
