### ISSUE TITLE
Improve file loading solution by using FileSystem API

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-html5#178]
Would that be a solution to our file loading lack of usability (one time it works in FF):
- Chrome filesystem api: https://developer.chrome.com/apps/fileSystem
- Overview article: http://www.html5rocks.com/en/tutorials/offline/quota-research/

**Comment by kelson42** [comment]
Maybe even a better documentation  http://www.html5rocks.com/en/tutorials/file/filesystem/

**Comment by mossroy** [comment]
Those links do not seem to talk about the same technology :  
- https://developer.chrome.com/apps/fileSystem is the chrome.fileSystem API, that can only be used by "Chrome apps" https://developer.chrome.com/apps/about_apps . It might be an option but I did not investigate. Of course, it's "Chrome apps"-specific.
- the links on html5rocks.com are about the HTML5 Filesystem API. It's also specific to Chrome (and Opera), see http://caniuse.com/#feat=filesystem, and the W3C dropped its standardization. But there is a big limitation : you can not access the actual filesystem of the user with this API. You only can access a sandboxed filesystem, where you can read and write files, but no other website/application can. I suppose that means the ZIM files have to be downloaded by the same URL that wants to read them.

I think the browsers will make it very difficult for us to read local files, for security reasons.
If we want to automatically load the ZIM files on startup, we'll probably have to run the HTML5/javascript outside of a classic browser : with something like Cordova, Chrome apps, or one of the solutions mentioned here : http://clintberry.com/2013/html5-apps-desktop-2013/ (might be outdated) or here : http://stackoverflow.com/questions/4869613/solutions-for-distributing-html5-applications-as-desktop-applications (might be slightly less outdated), or http://www.smartfeeling.org/desktopgap/

Some work with Cordova had already been commited on kiwix-html5 by @peter-x , with an Android port in mind. But it's still a work-in-progress.
I did not investigate any of the other candidates for now.

**Comment by mossroy** [comment]
I'm closing this issue as I don't think it's relevant for Kiwix : 
- the HTML5 FileSystem API allows access to a sandboxed virtual filesystem, with limited size and can only be accessed by the application itself. One can not transfer a ZIM file from a USB drive to the sandboxed filesystem, for example
- the Chrome apps have been deprecated by Google, expect for Chromebooks
