### ISSUE TITLE
Handle properly a content that would be split between several .zimnn files

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-html5#181]
The current implementation does not support it.
@peter-x has started a fix for that : see https://github.com/kiwix/kiwix-html5/pull/174/commits/4064b18456bf66f7422d4d36a134f53e5b04fa27#diff-007c0d1e629514c68435857c47963679
But I had to temporarily revert it because it introduced a big performance regression

**Comment by mossroy** [comment]
We might be able to create a unit test on that issue, after splitting the Ray Charles archive in several .zimnn parts, and opening an article that would be spread among 2 files.

**Comment by peter-x** [comment]
The current solution also only handles files with identical size. Accessing the files size might cause the regression.

**Comment by peter-x** [comment]
Hm, now that I had a look at it, I think it was not a performance regression but an actual error in the branch. I forgot to commit a fix - will push everything to an updated `issue113` branch, so you can take a look, because I did not notice a performance degradation.

**Comment by mossroy** [comment]
This has been fixed by PR #182
