### ISSUE TITLE
File picker should filter out non-zim files

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-html5#211]
At first the extensions asks for choosing a file and this is done through a traditional (from the browser/OS) file picker. Unfortunately the type filter is not set, so all files are displayed. Would be easier to pick a ZIM file, if only the ZIM files were displayed. I propose to setup a default file extension filter on *.zimm(aa)

**Comment by mossroy** [comment]
I need to let the user choose : 
- a .zim file
- a .zim* file (not only .zimaa beause he has to select all of them) : it's not possible to use * there, so I have manually listed all the .zima* (hopefully we never use more than 26 splitted files)
- the file types of Evopedia archives (still supported until #195) : *.dat, *.idx, *.txt
