### ISSUE TITLE
Feedback from exploratory testing on Chrome OS

### ISSUE THREAD

**Issue by julianharty** [kiwix/kiwix-html5#220]
Here's some initial feedback on how the extension works on Chrome OS. I may update this topic from time to time, others are welcome to add their comments and feedback.

I downloaded the extension from the Chrome Store. The initial impression was it loaded a bit slowly but then rendered adequately and told me enough to be able to visit the download.kiwix.org site to download a ZIM file, etc. I duly did so (a phet_en_ ZIM) however the subsequent experience was mixed. Content rendered quite slowly (perhaps 5 seconds) for the initial screen and then there wan't an obvious home page or anything that'd indicate what to do next (this may be an issue with the ZIM file which was one reason I later downloaded additional files to test with). The Random feature could find a topic and started loading that topic (PhET exercise) but the loading doesn't seem to get beyond the splash screen (with a PhET logo) and I've yet to see or try a PhET exercise on this Chrome OS device. I tried using the search but wasn't able to find any search results (the extension says `no files found`). 

I then used wikinews in English, April 2017. Again this renders slowly - multiple seconds. However Teresa May did eventually appear in all her glory - as well as the rest of the articles on the homepage of the ZIM file. Searches seem to work (there are some data quality issues in the ZIM file outside the scope of this testing) and content generally renders, albeit slowly.

I'll test one of the small TED talks to see how well audio and video are presented.

Here are various screenshots, it's impractical to filter or check them on Chrome OS when raising this issue so apologies for any duplicates.

![screenshot 2017-05-02 at 18 21 08](https://cloud.githubusercontent.com/assets/785891/25631209/97891130-2f67-11e7-89be-7332cedac986.png)
![screenshot 2017-05-02 at 18 17 29](https://cloud.githubusercontent.com/assets/785891/25631211/978b182c-2f67-11e7-8b5c-f5930640a5ce.png)
![screenshot 2017-05-02 at 18 13 24](https://cloud.githubusercontent.com/assets/785891/25631207/9788556a-2f67-11e7-9842-2339676cbd38.png)
![screenshot 2017-05-02 at 18 13 16](https://cloud.githubusercontent.com/assets/785891/25631210/978a81fa-2f67-11e7-84d9-679e5241bebb.png)
![screenshot 2017-05-02 at 18 12 56](https://cloud.githubusercontent.com/assets/785891/25631208/97888846-2f67-11e7-92a5-75e3ff4fff16.png)
![screenshot 2017-05-02 at 18 12 50](https://cloud.githubusercontent.com/assets/785891/25631212/9795441e-2f67-11e7-8455-914039840642.png)
![screenshot 2017-05-02 at 18 12 32](https://cloud.githubusercontent.com/assets/785891/25631215/97a70802-2f67-11e7-96d8-ae41d5e9d15a.png)
![screenshot 2017-05-02 at 18 12 22](https://cloud.githubusercontent.com/assets/785891/25631216/97a8705c-2f67-11e7-9f6e-8534809a61db.png)
![screenshot 2017-05-02 at 18 12 00](https://cloud.githubusercontent.com/assets/785891/25631217/97a926f0-2f67-11e7-9cb3-f39ad1281102.png)
![screenshot 2017-05-02 at 18 11 50](https://cloud.githubusercontent.com/assets/785891/25631214/97a71f7c-2f67-11e7-8bc4-910fc0d42926.png)
![screenshot 2017-05-02 at 18 11 47](https://cloud.githubusercontent.com/assets/785891/25631213/97a698f4-2f67-11e7-908f-3dadfadfa4b9.png)
![screenshot 2017-05-02 at 18 10 43](https://cloud.githubusercontent.com/assets/785891/25631218/97ae06de-2f67-11e7-8054-e16f19ff98af.png)

**Comment by julianharty** [comment]
As a detail, the file chooser says: Choose Files, yet we choose a single file at a time, so perhaps it'd be more appropriate to say 'Select File'?

**Comment by julianharty** [comment]
BTW Random works in wikinews - for PhET and the TEDx talks it's not practical to test it as neither displays the content. 

I used the TEDx Geneva ZIM, mainly as it's roughly 250MB so small enough to download and use. Sadly it's not rendered well and the content doesn't play (the content was found using Random). Searches was able to find a match once I knew what to search for (part of the title of the article selected by using Random). I've added 2 screenshots:
![screenshot 2017-05-02 at 18 49 57](https://cloud.githubusercontent.com/assets/785891/25631526/99a4c36e-2f68-11e7-86fc-097e1c64b09f.png)
![screenshot 2017-05-02 at 18 49 31](https://cloud.githubusercontent.com/assets/785891/25631521/993197ea-2f68-11e7-9695-bd7d0247000d.png)

**Comment by julianharty** [comment]
BTW: The images are displayed in reverse order compared to when I took them.

**Comment by mossroy** [comment]
Thanks a lot Julian for this testing and feedback.
Here are a few answers : 

- kiwix-html5 is not compatible with all ZIM files for now. I tested it almost only with wiki* contents. There are some bugs with other contents. See #205 for example. Maybe I should state that clearly inside the app. Moreover, audio, video, and javascript do not work at all for now. #172 and #152. So I'm not surprised PhET and TEDx do not work
- I know performance is really bad compared to the native Kiwix client. There are some ideas to improve that : #130, #149, #219, #116 
Except if we implement #116, it will always be difficult to catch up with libzim features and performance, because everything has to be reimplemented in javascript
- it's necessary to be able to select multiple files when using split ZIM files (.zimaa, .zimab etc.), when the filesystem can not handle large files
- if there is a home page configured in the ZIM file, it should open automatically, as it did for wikinews. It has been implemented at the end of the hackathon (#126). If you have a wiki*.zim file where the homepage opens in another Kiwix client, and does not in kiwix-html5, please file a bug

I don't see any ChromeOS-specific issues in what you reported. So I guess we can say kiwix-html5 is compatible with it, which is good news.
I'm sorry for the bugs and slowness. I opened #221 to avoid people using incompatible ZIM files.

**Comment by julianharty** [comment]
@mossroy You've done a great job to get the functionality to this level of completeness and something is better than nothing. Perhaps we'll find performant ways to cope with the various ZIM file structures? and perhaps we can also add detection code (where we query the ZIM file and determine how well we can support it). None of these are urgent in my view, more good to address when we can. 

Oh, and particularly for older Chromebooks that don't/won't have support for Android apps, this HTML5 project enables these users to use Kiwix for Wikimedia contents, even if it doesn't work for some of the other content.

**Comment by julianharty** [comment]
This may be a bit detailed and seem like an edge case, however it'd be good to address in the extension (possibly as a separate issue to stop it being lost here?)

When I use the content I create (from github.com/julianharty/testing-heuristics) the CSS doesn't get applied. When we generate the content we use `zimwriterfs --uniqueNamespace ...` so that the CSS can be found (well sort of at the moment). However, it seems that might cause some knock-on complications as the mime-type is now reported by Google Chrome as `text/html` (see below for the message Chrome Developer Console shows). The bug may be in `zimwriterfs` I'll cross-link the relevant issue. https://github.com/openzim/libzim/issues/15 I'll also zip the ZIM file and add it here (I can't attach it directly with a `.zim` extension).


```
Resource interpreted as Stylesheet but transferred with MIME type text/html: "chrome-extension://donaljnlmapmngakoipdmehbfcioahhk/www/A/style.css".
```

**Comment by julianharty** [comment]
Here's the ZIM file I used. It's zipped so will need unzipping before using it.
[th20170509.zim.zip](https://github.com/kiwix/kiwix-html5/files/985732/th20170509.zim.zip)

**Comment by julianharty** [comment]
OK, a quick test using my kiwix-apache module (which logs the filename and mime-type in Apache Server's `error.log`) indicates that the mime-type is set correctly for `./A/style.css` (at least as far as I can tell) 
```
[Tue May 09 07:50:59.397995 2017] [kiwix:notice] [pid 19337:tid 140382893475584]  ZIM file including path: /home/julian/Downloads/th20170509.zim
[Tue May 09 07:50:59.398025 2017] [kiwix:notice] [pid 19337:tid 140382893475584] full url = /kiwix/A/style.css, kiwix url = A/style.css
[Tue May 09 07:50:59.398182 2017] [kiwix:notice] [pid 19337:tid 140382893475584] contentType:[text/css]
```

The CSS is being applied correctly e.g. if I visit http://localhost/kiwix/A/I%20SLICED%20UP%20FUN.html (which will only work for you if you've got `kiwix-apache` setup to use the above ZIM file).

**Comment by mossroy** [comment]
I created a separate issue for that : #230

**Comment by mossroy** [comment]
I suppose I now can close this. Feel free to open new issues if you have more feedback
