### ISSUE TITLE
EMSCRIPTEN (xzdec.js) - buffer overrun on Windows 10 Mobile with very long articles

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-html5#253]
I've been investigating a suspected buffer overrun with the xzdec.js JS-compiled C++ code which happens on Windows 10 Mobile (only, not on full Windows 10) when loading a very heavy Wiki page. The page I've been using which reliably causes the buffer overrun is https://es.wikipedia.org/wiki/Bolivia (in wikipedia_es_all_2017-05.zim ). Quite a few other heavy pages cause the problem too. I suspected a limited memory environment, and it turns out to be the case. I can solve the problem by increasing the initial variable `TOTAL_MEMORY` assigned in xzdec.js, but only by modifying the module, which is a compiled one and presumably not one I should be "hacking". Is there a more elegant solution than the hack below?

**Details:**

I isolated the problem to this function in xzdec.js:
```
function enlargeMemory() {
    while (TOTAL_MEMORY <= DYNAMICTOP) { TOTAL_MEMORY = alignMemoryPage(2 * TOTAL_MEMORY) }
    assert(TOTAL_MEMORY <= Math.pow(2, 30));
    var oldHEAP8 = HEAP8; var buffer = new ArrayBuffer(TOTAL_MEMORY);
    Module["HEAP8"] = HEAP8 = new Int8Array(buffer);
    Module["HEAP16"] = HEAP16 = new Int16Array(buffer);
    Module["HEAP32"] = HEAP32 = new Int32Array(buffer);
    Module["HEAPU8"] = HEAPU8 = new Uint8Array(buffer);
    Module["HEAPU16"] = HEAPU16 = new Uint16Array(buffer);
    Module["HEAPU32"] = HEAPU32 = new Uint32Array(buffer);
    Module["HEAPF32"] = HEAPF32 = new Float32Array(buffer);
    Module["HEAPF64"] = HEAPF64 = new Float64Array(buffer);
    HEAP8.set(oldHEAP8);
    var success = _emscripten_replace_memory(buffer); assert(success)
}
```
After iterating that loop on the "Bolivia" page about three times, the line `HEAP8.set(oldHEAP8);` throws an exception and after that memory is corrupted and the app has to be exited and restarted to load anything further at all. Fortunately apps are rigorously sandboxed, so this is an inconvenience more than a security concern, I think.

After reading up on EMSCRIPTEN, which is the compiler here, I traced `TOTAL_MEMORY`, and found that it increases too rapidly because its startup value is too low. After experimenting with various values, here is what I did to solve it:
```
//var TOTAL_MEMORY = Module["TOTAL_MEMORY"] || 8e7; //- GK not enough startup memory
var TOTAL_MEMORY = Module["TOTAL_MEMORY"] || 14000000;
```
With the hex value of 14000000, the phone iterates the above loop only twice in the page load (increasing the dynamic value further) and the page finishes loading correctly.

Any thoughts on a better way to solve it? I'm wondering whether `TOTAL_MEMORY = Module["TOTAL_MEMORY"] || 8e7;` would allow me to set `TOTAL_MEMORY` in an external module. But I can't find anything referenced by `Module["TOTAL_MEMORY"]`.

**Comment by Jaifroid** [comment]
Further info on potential security concerns: see https://palant.de/2017/04/23/how-bad-is-a-buffer-overflow-in-an-emscripten-compiled-application , and particularly the issue of zero-terminated response strings towards the bottom of that page.

**Comment by mossroy** [comment]
When I run Kiwix on a desktop browser, the console logs something like : 
increasing TOTAL_MEMORY to 83886080 to be more reasonable
Based on https://www.bountysource.com/issues/5115681-increasing-total_memory-to-x-to-be-more-reasonable-should-be-more-descriptive , I understand that emscripten modifies this TOTAL_MEMORY by itself (maybe based on the capacities of the browser/device).
When you don't modify this variable value in the code, can you read this console log from your device, to see which amount of memory it chooses to use?
If I have time, I should try to see which amount is used on a Firefox OS device.
If 14000000 is an hex value, it means around 335 MB? It seems to be a lot?

Based on https://groups.google.com/forum/#!topic/emscripten-discuss/6Sox46w_TfY , there seems to be different strategies that Emscripten can use to increase memory usage.
Maybe switching to another strategy could help.
Or simply recompiling it with a more recent version of emscripten.

Unfortunately, I have to say that it's a part I don't master.
The emscripten compilation had been made by @peter-x , who does not actively work on the project any more.

**Comment by Jaifroid** [comment]
Yes, I've seen that message with the variable set to 8e7 on some pages, but the way I arrived at 14000000 was by watching the TOTAL_MEMORY variable while debugging. It self-increased multiple times while loading the Bolivia article on my test device (Lumia 950XL) during test runs. I need to experiment with lower starting values because I agree that this is a lot of memory to be assigning up-front for someone who might only be reading a small ZIM file and a light-weight article. I also need to check whether reading from a split ZIM file has the same memory requirements, i.e. whether this has anything to do with repeated access to a 15GB ZIM file on a phone's microSD card.

I posted this bug here rather than in kiwix-html5-windows because the buffer overrun may have security implications for those running the app in a browser on other platforms.

**Comment by Jaifroid** [comment]
Ha, I've discovered something interesting. All the memory variables are in fact decimal, not hex, but in this module TOTAL_MEMORY is set with a starting value of 8E7, which is what led me to believe it was hex. However, setting larger hex values with letters in them causes a lockup, and looking at the subroutines, they're all being manipulated as decimal, e.g.:
```
while (totalMemory < TOTAL_MEMORY || totalMemory < 2 * TOTAL_STACK) {
    if (totalMemory < 16 * 1024 * 1024) { totalMemory *= 2 } else { totalMemory += 16 * 1024 * 1024 }
}
```
It looks like during compilation with `-s TOTAL_MEMORY=<number>`, someone entered a HEX value in error, unless there's something else I'm missing here.

Just changing the TOTAL_MEMORY startup value to `0x8e7` allows me to load the Bolivia page without the buffer overrun!

@mossroy it looks like we'll need to change this value in you upstream, as it looks to me like a bug. Can you corroborate? In the meantime, I'm going to commit this change to kiwix-html5-windows, as on W10M it's a blocking bug.

**Comment by mossroy** [comment]
Great analysis!
I did not look in details, but you're probably right.
I'm wondering where this 0x8e7 value comes from...

In any case, I think it should be worth creating a PR here for that, so that we can test (on Firefox OS devices for example, where there is not much memory available), and hopefully merge it here.
0x8e7=around 2KB, which is much less scary than 335MB ;-)

**Comment by Jaifroid** [comment]
Thanks @mossroy .

I've created a new branch Test-TOTAL_MEMORY-values-xzdec.js for testing this, but I haven't PR'd it yet. The xzdec.js file is minified (it was originally, I didn't minify it) so the diffs will look terrible. However, you can view the bit I've inserted for checking by going here:

https://github.com/kiwix/kiwix-html5/blob/Test-TOTAL_MEMORY-values-xzdec.js/www/js/lib/xzdec.js

Maybe test this branch before doing PR? If that's not how it works, fine, I can PR that branch (or feel free to do it yourself, if that doesn't create review problems).

**Comment by Jaifroid** [comment]
Regarding the 0x8e7 value, it's too small for W10M, and immediately starts increasing dramatically on any page load. I wonder if the original compiler of this meant 8e70 (36KB) or even 8e700 (583KB).  I've opened an issue for this here: https://github.com/kiwix/kiwix-html5-windows/issues/7 which has a link to the EMSCRIPTEN specs, but I believe a higher value should be tested on different platforms. I'll obviously test W10M thoroughly.

**Comment by sharun-s** [comment]
@jaifroid I have been wondering why xzdec_wrapper defines a chunk size of 5KB, and whether increasing that to the size of the blob (that needs to be decompressed) will reduce the number of unnecessary reads (at least for large file reads). Any thoughts on that?

**Comment by Jaifroid** [comment]
@sharun-s  That sounds plausible to me! Can you post here the specific bit of code you'd suggest tinkering with? I think you have more of an understanding of what's going on here than I have -- I just debugged a very specific subroutine that was causing some pages to crash the kiwix-html5-windows version, which is why I came across this issue. I'd like to try to optimize disk reads and memory usage, because the app will otherwise come across as sluggish to users.

**Comment by Jaifroid** [comment]
@sharun-s Could we define `Module["TOTAL_MEMORY"]` in xzdec_wrapper, to allow for different values per OS? It looks like setting `xzdec.TOTAL_MEMORY` *might* do the job. (This isn't related to the chunk size issue you raised.)

**Comment by sharun-s** [comment]
@Jaifroid I hadn't thought to look into xzdec itself until I saw your posts. I did find multiple decompressions happening for small blobs 10-15K which I thought was unnecessary. But then I have no idea how xzdec works and if the 5KB chunk size was some magic optimal number.  

If you want to play around with it you have to tinker with zimArchive.readArticle.  

To visualize how many decompressions are happening simplest way I found was using the js profiler tab of Chrome devtools. 

Modify tests.js to run just one [test](https://github.com/kiwix/kiwix-html5/blob/master/tests/tests.js#L125) that was making the readArticle call. 
You can skip/delete all the other tests.   
Place a console.profile("readArticle") just before readArticle gets called on  line 137
And a console.profileEnd("readArticle") just before done() on line 135. 
Then run tests.html
 
You will see the 5 decompressions happening to read the ~20KB blob as in the image below. 

You can play with changing the chunk size when decompressor is [created ](https://github.com/kiwix/kiwix-html5/blob/master/www/js/lib/zimfile.js#L196) by passing it as the second arg(currently not used) plus some small change in the wrapper which I forget know. 
Clicking on the purple bars will take you to the code and you will be able to understand the flow how the chunking is happening.
![decomps](https://user-images.githubusercontent.com/18413274/27286646-8b914b22-551e-11e7-9e70-1ae95450e539.png)

**Comment by Jaifroid** [comment]
That's very helpful diagnostic info @sharun-s  .  In the meantime I had tried out the following in the app (from xzdecwrapper.js):
```
    function Decompressor(reader, chunkSize) {
        //this._chunkSize = chunkSize || 1024 * 5;
        this._chunkSize = 1024 * 25; // Test
        this._reader = reader;
    };
```
However, this increases the memory requirements inside xzdec, maybe unsurprisingly, causing the buffer overrun issue to return. It seems the chunkSize here is by default set at 5Kb precisely to allow for multiple small reads from the file without consuming too much memory. As it is, on large ZIM files with image-heavy pages, the app consumes lots and lots of memory on WM10 -- I've seen JavaScript memory usage go to 957Mb with the full Spanish all images Wikipedia file on really heavy pages (clearly this isn't the page size, but all these simulated C++ stacks). Ray Charles uses max 300Mb.

**Comment by sharun-s** [comment]
that's nuts...after going up to 957 does it stay there for subsequent page loads/or keeps rising/or drops and rises?

**Comment by Jaifroid** [comment]
Memory drops down to about 700MB for the huge file and page loads, but not back to the initial 150KB which the app starts with, and not back to the 300MB Ray Charles uses.

It's definitely the dynamic expansion loop in xzdec.js which keeps asking for more and more memory on a very heavy page. It looks as if the memory isn't getting freed up or re-used after each BLOB read. Maybe because that would be too slow?

I think this reinforces the need for #219 (Recompile xzdec.js in Web Assembly). I think this is needed quite urgently.

**Comment by mossroy** [comment]
Keep in mind that WebAssembly is not supported everywhere : http://caniuse.com/#feat=wasm
(but I was told that emscripten was able to generate the asm.js code as a fallback)

**Comment by mossroy** [comment]
Maybe simply recompiling the C library in asm.js to re-generate the javascript xzdec could benefit from the latest enhancements of emscripten?

**Comment by Jaifroid** [comment]
> Keep in mind that WebAssembly is not supported everywhere : http://caniuse.com/#feat=wasm (but I was told that emscripten was able to generate the asm.js code as a fallback)

Yes it looks like a future technology atm, and, for my immediate purposes, it is not (yet?) supported in UWP. I guess the preferred method in UWP HTML5 development would be to compile a C++ component into Windows Runtime and "consume" it from the JavaScript application. But that's outside of the realm of a cross-platform HTML5 app, quite apart from it being very difficult to write the interface between JS and the C++ component.

> Maybe simply recompiling the C library in asm.js to re-generate the javascript xzdec could benefit from the latest enhancements of emscripten?

I read that you can't use the dynamic memory expansion and retain the asm optimization. But there might be other optimizations in recompiling with the latest version. Did @peter-x leave any documentation on the metafiles needed to expose specific XZ-Embedded functions to JavaScript? It would be a shame to have to reinvent the wheel.

As a kludge, I'm testing changing `"almost asm"` to `"use asm"` in xzdec.js. I read somewhere that this "sometimes" works to signal to the JavaScript engine to use optimized execution. It runs in Edge, subjectively "seems faster", but I think it's placebo until I can do a proper test, a bit like you found with the caching code. However, it doesn't change the memory footprint, which is my main concern at the moment. Memory use jumps exponentially with a larger number of calls to xzdec (i.e. with lots of images, JS and CSS).

There seems to be a significant slowdown around the jQuery substitutions. For a few regex search and replaces, why use jQuery? I know it wouldn't be asynchronous, but it should be faster, once we have the HTML of the article page, just to throw a bunch of regexes at it to do the substitutions. Regexes are blazing fast in native JavaScript. The CSS code in `$('#articleContent').contents().find('link[rel=stylesheet]').each(function()` seems particularly slow, and much slower, oddly, than the equivalent code for images. It takes forever to find the CSS references. Is this because the CSS is stored somewhere at the end of a 15GB file? However, even with a Ray Charles article, the insertion of the CSS creates a noticeable delay after all the images have loaded. There must be some scope for optimization here.

**Comment by mossroy** [comment]
It's a "future" technology for Edge, but just a "recent" technology for Firefox and Chrome.
Sorry for the troll ;-)

As you said, I think it's better to keep a croos-platform HTML/js app.
Regarding recompiling xz decoder with emscripten, it might not be that complicated, as it does not seem to have a lot of dependencies.
It also looks like someone else already compiled a XZ decoder in asm.js : https://github.com/yurevich1/xz-pure-js-web-worker . It might be possible to switch to this implementation instead of ours, to see how it behaves. It runs inside a webworker, which might help improve our performance. I created #259 for that.

Regarding the jQuery usage, there's certainly room for performance improvement.
But jQuery does not parse the ZIM file itself : only the DOM of the HTML article. So the performance to inject CSS should not depend on the size of the ZIM, but on the size of the HTML article.

**Comment by mossroy** [comment]
@sharun-s , could you give me your email at mossroy@mossroy.fr?
I just invited you as a member of the Kiwix team, like @Jaifroid recently had.
It gives both of you write access to the the repo, so I'd like to discuss with you about how to collaborate efficiently together.

**Comment by sharun-s** [comment]
Ran across this comment  on openzim https://github.com/openzim/libzim/issues/77#issue-271300505 that seems to explain why multiple decompressions happen even for small files. 

It seems to suggest lzma2 has a fixed block size that it decompresses no matter what the actual data size being read is. And recommends small files remain uncompressed in the zim to reduce number of decompressions reqd. It is probably true that lot of zim's/zim creators (with files smaller than the lzma block size) are unknowingly compressing all files (big or small). It's also possible that in some cases lzma block size used is different. 

So I am guessing nothing much can be done on the client side to optimize number of decompression reads. Other to know why sometimes you will find multiple decompressions happening for nonobvious reasons. Just documenting it here and it probably is good to know wrt #288 and other issues were xzdec is involved.

**Comment by Jaifroid** [comment]
Hi @sharun-s , I'm not sure if this is related, but @mossroy managed to recompile xzdec -- see https://github.com/kiwix/kiwix-js/issues/219 -- and I also recompiled with several different settings. We've come up with an asm-enabled version that only supports decompressing serially, i.e. it doesn't attempt parallel decompression. Parallel decompression was only ever an illusion, except in the case of Web Workers, as there is only one main thread. 

It turns out that the code was churning a lot when sent multiple blobs to decompress. So we've refactored the code of Kiwix JS to wait for the decompressor to be free before sending any more blobs -- see https://github.com/kiwix/kiwix-js/pull/398 . The outcome of all of this is greatly increased performance. At last we can decompress Wilson-Cowan Model (in Wikimed) or Sine.html pretty fast and with no crashes. Note that Kiwix JS Master doesn't yet have the new xzdec incorporated, but I've tested it extensively in Kiwix JS Windows, and it's actually in the production version of Kiwix JS Windows since https://github.com/kiwix/kiwix-js-windows/commit/5f8c435e43d24ac3abbc8351128e240dd148bc87  with no ill effects. There is also potentially a very fast wasm version of xzdec, though it's only marginally better than asm in my testing, and introduces backward compatibility issues.

**Comment by sharun-s** [comment]
Thanks @Jaifroid will take a look at what the new code is doing. I was looking again at this xzdec/decompression stuff while trying to get video in the ted talks zim to work. Felt like a similar loop involved decoding video in chunks, and thats when I ran into the openzim comment.
