### ISSUE TITLE
Optimize bzip2 decoding, if possible

### ISSUE THREAD

**Issue by mossroy** [kiwix/kiwix-html5#4]
Uncompressing an article is very slow on a device : usually around 5s on a Geeksphone Peak.

But I think this will be hard to improve.
Maybe another javascript implementation : https://github.com/kirilloid/bzip2-js or https://github.com/skeggse/node-bzip/blob/master/node-bzip/index.js
The bzip2 compression format seems to support multi-core decoding. On the Peak device, it would be useful (dual-core CPU), but I think that all these javascript implementations do not support multi-core decoding
A better way to optimize this would be to have a b2g API like https://wiki.mozilla.org/WebAPI/ArchiveAPI. But that does not seem to be planned by Mozilla for now...

**Comment by mossroy** [comment]
I close this issue as "wontfix" : the Evopedia archive format is now deprecated

**Comment by cscott** [comment]
FWIW, I wrote seek-bzip and compressjs for https://github.com/cscott/nell-wikipedia, so it's not surprising they seemed suited for your uses. ;)
